# Generated by Django 2.1.7 on 2019-02-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pug_or_ugh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPref',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=1)),
                ('gender', models.CharField(max_length=1)),
                ('size', models.CharField(max_length=2)),
            ],
        ),
    ]
